name: tests

on:
  push:
    branches:
      - 'feature/**' # Tests for spruce branches (For example, feature/new-model)
  pull_request:
    branches:
      - 'main'      # Tests when creating PR in Main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"] # Python versions for testing
        os: [ubuntu-latest, macos-latest, windows-latest] # Testing with different OS

    steps:
      - uses: actions/checkout@v4  # Clone repository

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with test

      - name: Run tests with coverage
        run: |
          poetry run pytest tests/ --cov=frameon --cov-report=xml --verbose

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  
          files: coverage.xml
          flags: unittests 
          verbose: true  
          branch: main
          override_branch: main
          env_vars: PR_NUMBER=${{ github.event.pull_request.number }}    
          commit_parent: ${{ github.event.pull_request.base.sha }}      
